### ISSUE TITLE
Plans for GraphQL Support

### ISSUE THREAD

**Issue by stuible** [dodecastudio/craft-blurhash#1]
Thank you so much for bringing this helpful utility to Craft CMS.  I would love to be able to access it via GraphQL, is there any plan to do so?

**Comment by tomkiss** [comment]
Hi Josh, 

Thanks for your feedback and great suggestion.

I'm somewhat strapped for time, but if I can find time, or tie this into some client work, then I'd love to implement this. I'll mark this as an enhancement and hopefully I can do this at some point in the future.

Thanks again!

**Comment by tomkiss** [comment]
Hey @stuible, well I found some time today and have just released [v1.1.0](https://github.com/dodecastudio/craft-blurhash/releases/tag/v1.1.0) with [Graph QL Support](https://github.com/dodecastudio/craft-blurhash#graphql-support).

Have a play, do please let me know if you find any problems 😀

**Comment by stuible** [comment]
This is perfect, thanks again for this plugin, it's saved me so much time!
