### ISSUE TITLE
Version 2.0.2 seems to break GraphQL

### ISSUE THREAD

**Issue by olsp** [dodecastudio/craft-blurhash#15]
After updating to 2.0.2 my GraphQL query doesn't work any longer. I get the following error: 
`dodecastudio\\blurhash\\qgl\\directives\\AssetToBlurHash::apply(): Return value must be of type string, null returned"`

After downgrading to 2.0.1, it works again.

In the query, I use
`blurhashUri: url @assetToBlurHash`

**Comment by tomkiss** [comment]
Hey @olsp 

Sorry about that. I could repro this locally - give 2.0.3 a whirl and let me know how you get on.

**Comment by olsp** [comment]
Thanks, works again!
