### ISSUE TITLE
@assetToBlurHash fails when using a dev server on plain HTTP trying to retrieve an asset over HTTPS to generate a BlurHash

### ISSUE THREAD

**Issue by HalCodes** [dodecastudio/craft-blurhash#16]
Your plugin is great!  Only a small problem, when I'm trying to use it on a local Craft Nitro dev environment that is running over plain HTTP, the blurHash fails with an empty string, probably related to an SSL connect error when trying to grab assets over HTTPS.

If you are using cURL behind the scenes, you might just need to add an `-k/--insecure` flag which would allow retrieving the assets.

This way local dev environments will have the same functionality as proper Staging or Prod environments over HTTPS.

**Comment by tomkiss** [comment]
Hi @HalCodes and thanks for reporting your issue.

Hmmm, I can't be sure why you're not receiving a value back. On my local ddev install I have the plugin running across HTTP and HTTPS, on Craft 3 & 4. If I use Craft's Graph QL explorer I can run the `resources/demo.graphql` example in all instances with no issue. 

Could you please confirm exactly what you're doing here?
I take it you are running a Graph QL query on an asset to retrieve a blurhash. Is it failing in the Graph QL explorer, or elsewhere?

**Comment by HalCodes** [comment]
Interesting. I will reconfirm and let you know

**Comment by HalCodes** [comment]
My bad.  The problem is that in my local environment, the assets are mapped to a (non-existant) volume.  So although the URL would populate on a GraphQL call, the actual image URL is a 404.  Which is why your plugin couldn't produce a blurhash for it and provided an empty string instead.  Problem solved!

**Comment by tomkiss** [comment]
Great, glad you managed to figure it out ☺️
