### ISSUE TITLE
Why is default blurredMaxImageSize so high?

### ISSUE THREAD

**Issue by acalvino4** [dodecastudio/craft-blurhash#19]
The default value of `blurredMaxImageSize` is 64, which results in a 3kb data uri string for many of my images. While this is of course small for an image, it is huge to be inlining in the html, especially if there are many images on a page.

Of course I can modify this to something smaller with the config, but this is more a question of whether that is an appropriate change to make.

I set `'blurredMaxImageSize' => 4,`, and in my markup have `"background: url({{ blurhash(image[0]) }}) center center / cover;"`, which results in a placeholder of only 150 bytes, that looks like this:

<img width="1106" alt="image" src="https://github.com/dodecastudio/craft-blurhash/assets/43254861/47c7c5b5-3475-4cd1-b874-fe814b95f42c">

Obviously this doesn't have as much detail as a 64px wide blurred image, but there is no pixelation in the way the browser renders it. Is the only reason then to generate a larger size to have more detail in the blurred image? Or are there some browsers that will render this extremely low quality image in a pixelated way?

**Comment by tomkiss** [comment]
Hi Augustine, thanks for your message.

There will be differences with different sizes. It's worth testing on a wide range of images to see any potential differences the setting impacts. 
There may be differences between browsers, or there could be situations where more pixels are necessary. Perhaps if you're rendering the image outside of a browser (via GraphQL to an app), you might want more pixels?

Closing as it's a discussion topic, but feel free to continue discussion :)
