### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by mihob** [dodecastudio/craft-blurhash#20]
Just checking, do you have plans for craft 5 support?

**Comment by tomkiss** [comment]
Yes, I will be looking to port to Craft 5, hopefully in the next 8 weeks.

**Comment by amkdev** [comment]
I would also be very happy about a Craft 5 version. Thanks in advance.

**Comment by tomkiss** [comment]
Hi there,

I've just released v3.0.0 which supports Craft 5. Tested on Craft 3, 4 and 5 - but please let me know if you see any issues at all. 

Thanks!

https://github.com/dodecastudio/craft-blurhash/releases/tag/v3.0.0

**Comment by mihob** [comment]
Awesome, thanks!
