### ISSUE TITLE
blurhash size / aspect ratio

### ISSUE THREAD

**Issue by olsp** [dodecastudio/craft-blurhash#5]
Hi,
is it possible to set the size, the blur hash should have? All the blur hashes I generate are 64x64px big. I need to keep the original aspect ratio of the image.

**Comment by tomkiss** [comment]
Hey,

This is possible, yes. This is also a really good suggestion!
I don't know why on earth I never thought to do it - so, thank you.

I'll have a think about how to implement it and do so when I get a chance.

😀

**Comment by tomkiss** [comment]
OK, @olsp - [1.2.2](https://github.com/dodecastudio/craft-blurhash/releases/tag/v1.2.2) adds this.

Note the README though - 
```html
<img src="{{ blurhash(testAsset) }}" width="{{testAsset.width}}" height="{{testAsset.height}}" style="aspect-ratio: {{testAsset.width}} / {{testAsset.height}};" />
```

> Note: Due to the compact dimensions of the blurhash image, its aspect ratio may differ fractionally from the source material. Ensure any image markup correctly renders the aspect ratio based on the source markup if you are trying to prevent [CLS](https://web.dev/cls/). One way to achieve this is to use the [CSS aspect-ratio property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio)[](https://github.com/dodecastudio/craft-blurhash/issues/5#other-features), as used in the example above.

And just to explain a little, the blurhash image _could_ be rendered larger than 64px max h/w, which would potentially make the aspect ratio more accurate. However, it would not really affect the quality of the blurhash image but would add processing time to the plugin. So it's a little bit of a balancing act.

Thanks for the suggestion and let me know if you have any problems.

**Comment by olsp** [comment]
Thank you so much. You just planted 100 trees ;-)

**Comment by tomkiss** [comment]
Fantastic! Thank you 😀

**Comment by olsp** [comment]
Hi Tom!
I'm having an issue with this. When creating the img src like this `blurhash( asset )`, it works fine. I'm storing the blur hash string in a field, and therefor I create the blurhash with `asset | blurhash` and later use `src="blurhashToUri( blurhashfieldname )"`. The first and second way should provide the same image src, shouldn't it? When using the blurhash filter, I still get a square image regardless the original aspect ratio.

**Comment by tomkiss** [comment]
Hi @olsp,

Hmmm, this is as expected. The Blurhash string itself doesn't contain any dimension data (this is just how [Blurhash](https://blurha.sh) works). 

When using `blurhash(asset)`, naturally the asset dimensions are available from the asset and the plugin can use these when generating the img tag. But when using `blurhashToUri()`, it's just the Blurhash string with no context of the original asset or its dimensions.

So, in order to render the blurhash image at the dimensions of the original asset, you'll need to store the asset's width and height, or perhaps an aspect-ratio, along with the blurhash string. If you wanted to be lightweight, you could consider doing this with a [Preparse Field](https://plugins.craftcms.com/preparse-field).

**Comment by olsp** [comment]
Thanks for your quick response.

I'm not sure if I get it right. So those two images are deliberately not the same?

```
{{ tag('img', {
    src: blurhash( asset ),
    alt: "",
    class: "blurhash",
    width: asset.width,
    height: asset.height,
    style: "aspect-ratio: " ~ asset.width ~ " / " ~ asset.height
}) }}

{{ tag('img', {
    src: blurhashToUri( asset | blurhash ),
    alt: "",
    class: "blurhash",
    width: asset.width,
    height: asset.height,
    style: "aspect-ratio: " ~ asset.width ~ " / " ~ asset.height
}) }}
```

If so, that's fine for me. I will look into the Preparse Field, didn't know about this plugin.

**Comment by tomkiss** [comment]
Yes, that's right!

Once is generating a Data URI image resource from an asset, using its dimensions to ensure an approximate aspect ratio.
...and the other is generating a Data URI image resource from a blurhash string, without any context as to the size of the original image.

:)
